version: "3"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.20
    container_name: es
#    environment:
#      discovery.type: "single-node"
#      bootstrap.memory_lock: "true"
#      "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
#    volumes:
#      - esdata1:/usr/share/elasticsearch/data
  web:
    build: .
    image: foodtruckcontainer.azurecr.io/umbhau/foodtrucks
    command: python3 app.py
#    environment:
#      - DEBUG=True
    links:
      - es
    ports:
      - 5000:5000
#    volumes:
#      - ./flask-app:/opt/flask-app
#volumes:
#    esdata1:
#      driver: local
